Module-2/Tasks-1-2-3
js-tasks-ru/jsbasic-20220124_mariya73 pull request #3
Opened 2022-02-06 15:53 UTC by alisam1

Module-2/Tasks-1-2-3

2022-02-06 15:54 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2022-02-06 16:42 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2022-02-06 17:10 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2022-02-06 17:46 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-02-07 05:20 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-02-07 05:21 UTC, koalex requested changes
Нужно решить `3-module/4-task` чтобы я смог принять этот PR.

2022-02-07 20:23 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2022-02-08 04:09 UTC, koalex approved these changes

2022-02-08 04:10 UTC, merged